name: all_lucky
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_compass: ^0.8.0
  geolocator: ^13.0.2
  logger: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  share_plus: ^10.1.4
  go_router: ^14.6.3
  http: ^1.2.1
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  test: ^1.24.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/horoscope/
    - assets/images/zodiac/ 