name: all_lucky
description: "A modern Chinese almanac app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # 狀態管理
  flutter_riverpod: ^2.4.9
  
  # 路由管理
  go_router: ^13.1.0
  
  # 網絡請求
  dio: ^5.4.0
  
  # 本地存儲
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  
  # 國際化
  intl: ^0.19.0
  
  # 工具
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 