name: all_lucky
description: 萬年曆運勢 App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  path: ^1.8.3
  meta: ^1.11.0
  collection: ^1.18.0
  async: ^2.11.0
  logging: ^1.2.0
  sqlite3: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  lunar: ^1.7.2
  encrypt: ^5.0.3
  fl_chart: ^0.65.0
  sensors_plus: ^4.0.2
  flutter_riverpod: ^2.4.10
  flutter_compass: ^0.8.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  timezone: ^0.9.2
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^16.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.0.1
  go_router: ^13.0.0
  riverpod_annotation: ^2.3.3
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  flutter_test:
    sdk: flutter

dev_dependencies:
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/zodiac/
    - assets/images/scenes/
    - assets/icons/
    # - assets/fonts/
    
  # fonts:
  #   - family: NotoSansTC
  #     fonts:
  #       - asset: assets/fonts/NotoSansTC-Regular.otf
  #       - asset: assets/fonts/NotoSansTC-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansTC-Bold.otf
  #         weight: 700 