name: all_lucky
description: "A modern Chinese almanac app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # 狀態管理
  flutter_riverpod: ^2.5.1
  
  # 路由管理
  go_router: ^14.6.3
  
  # 網絡請求
  dio: ^5.4.1
  
  # 本地存儲
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  
  # 國際化
  intl: ^0.20.1
  
  # 工具
  collection: ^1.18.0
  meta: ^1.11.0
  
  # 農曆計算
  lunar: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 