name: all_lucky
description: A lucky fortune telling app
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  http: ^1.2.1
  path: ^1.9.0
  meta: ^1.11.0
  collection: ^1.18.0
  async: ^2.11.0
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/zodiac/
    - assets/icons/
    # - assets/fonts/
    
  # fonts:
  #   - family: NotoSansTC
  #     fonts:
  #       - asset: assets/fonts/NotoSansTC-Regular.otf
  #       - asset: assets/fonts/NotoSansTC-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansTC-Bold.otf
  #         weight: 700 