name: all_lucky
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.3
  logger: ^2.0.2+1
  lunar: ^1.6.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true 